"""Inital schema

Revision ID: 6dc52e6a9241
Revises: 
Create Date: 2026-06-03 20:02:06.981874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc52e6a9241'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='document_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_status'), 'document', ['status'], unique=False)
    op.create_table('processing_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('processing_type', sa.Enum('DOCUMENT_SUMMARY', 'INVOICE_EXTRACTION', 'CONTRACT_METADATA', name='processing_type'), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='processing_status'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_request_document_id'), 'processing_request', ['document_id'], unique=False)
    op.create_index(op.f('ix_processing_request_status'), 'processing_request', ['status'], unique=False)
    op.create_table('extracted_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('processing_request_id', sa.Integer(), nullable=False),
    sa.Column('result_type', sa.String(length=100), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['processing_request_id'], ['processing_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processing_request_id')
    )
    op.create_table('processing_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('processing_request_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('worker_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'RETRYING', 'COMPLETED', 'FAILING', 'DEAD_LETTER', name='processing_job_status'), nullable=False),
    sa.ForeignKeyConstraint(['processing_request_id'], ['processing_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_job_processing_request_id'), 'processing_job', ['processing_request_id'], unique=False)
    op.create_index(op.f('ix_processing_job_status'), 'processing_job', ['status'], unique=False)
    op.create_index('ix_processing_job_status_attempt', 'processing_job', ['status', 'attempt_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_processing_job_status_attempt', table_name='processing_job')
    op.drop_index(op.f('ix_processing_job_status'), table_name='processing_job')
    op.drop_index(op.f('ix_processing_job_processing_request_id'), table_name='processing_job')
    op.drop_table('processing_job')
    op.drop_table('extracted_result')
    op.drop_index(op.f('ix_processing_request_status'), table_name='processing_request')
    op.drop_index(op.f('ix_processing_request_document_id'), table_name='processing_request')
    op.drop_table('processing_request')
    op.drop_index(op.f('ix_document_status'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
