"""v4_add_updated_at_column_to_document_schema

Revision ID: a94106db4837
Revises: b71b7c338237
Create Date: 2026-07-14 19:43:15.198003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94106db4837'
down_revision: Union[str, Sequence[str], None] = 'b71b7c338237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'updated_at')
    # ### end Alembic commands ###
