"""v2_update_job_status_enum

Revision ID: e50385be98bd
Revises: f13bb5d6f779
Create Date: 2026-06-15 17:14:12.811985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e50385be98bd'
down_revision: Union[str, Sequence[str], None] = 'f13bb5d6f779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE processing_job_status ADD VALUE 'FAILED'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE processing_job_status "
        "RENAME VALUE 'FAILING' TO 'FAILED'"
    )
    # ### end Alembic commands ###
