"""v1_add_file_schema

Revision ID: f13bb5d6f779
Revises: 6dc52e6a9241
Create Date: 2026-06-04 11:24:13.390618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f13bb5d6f779'
down_revision: Union[str, Sequence[str], None] = '6dc52e6a9241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('extension', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('document', sa.Column('file_id', sa.Integer(), nullable=False))
    op.create_unique_constraint("uq_document_file_id", 'document', ['file_id'])
    op.create_foreign_key("fk_document_file_id", 'document', 'file', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_document_file_id", 'document', type_='foreignkey')
    op.drop_constraint("uq_document_file_id", 'document', type_='unique')
    op.drop_column('document', 'file_id')
    op.drop_table('file')
    # ### end Alembic commands ###
